version: '2'
services:
  msaapp001-app:
    image: msaapp001
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@192.168.1.25:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@192.168.1.25:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.1.25:3306/msaapp001?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
      - SPRING_DATA_JEST_URI=http://192.168.1.25:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://192.168.1.25:9200
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=192.168.1.25
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=192.168.1.25
    ports:
      - 9092:9092
